version: 2

references:
  container_config: &container_config
    working_directory: ~/root
    docker:
      - image: heug/docker-images:fundthatflip
  
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: "echo "DONE"

