version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
      - image: mysql:5.7
      - image: elasticsearch:1.4
        command: sleep 5
    working_directory: ~/root
    steps:
      - checkout
      - run: "echo "DONE"
