version: 2

references:
  container_config: &container_config
    working_directory: ~/root
    docker:
      - image: circleci/node:6
      - image: mysql:5.7
      - image: elasticsearch:1.4
        command: sleep 5
  
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: "echo "DONE"
      